let data = [
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.19_19d99409.jpg",
    title: "Vishnu",
    dsc: "Within the eastern Indian sculptures, distinctive regional styles are discernible particularly in the images from the region of Dacca, Kurkihar, Nalanda and Vikramshila.\nThe present haloed four-armed Vishnu accompanied by his two consorts, is standing in Samabhanga pose on a full-blown lotus. Standing to his left is Saraswati, the goddess of knowledge and to his right, Shridevi, holding chauri in her right hand and lotus stem in her left hand. In his four hands, he holds the shankha, chakra, gada and padma. He is adorned with a crown, necklaces and other ornaments with a vanamala reaching his knees.\nOn either side of the pedestal shankha purusha and Gada devi are shown. Seated male and female devotees with folded hands appear on either side below.\nThe Prabha is decorated with gaja-vyalas, hamsas, makaras, flying vidyadharas and floral motifs and surmounted with kirtimukha.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "11th Century CE",
    location: "Bengal",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.20_8de50130.jpg",
    title: "Gajalakshmi",
    dsc: "Two-armed Gajalakshmi depicted here seated on a lotus pedestal in lalitasana. She wears a short mukuta, necklace, armlets, anklets and large elaborate akshamala. She holds a lotus flower in her left hand while the right hand rests in varadamudra. Two female attendants are seated on a lotus stalk on either side of Gajalakshmi. Each of them holding a kalasha in their hands. A pair of elephants each holding a kalasha in its trunk is bathing Lakshmi.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "8th- 9th Century CE",
    location: "North India",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.18_7926def2.jpg",
    title: "Buddha",
    dsc: "The Buddha is seated in dhyana-mudra (meditative posture) on a lotus pedestal, with an oval-plate Prabha is attached to it. The Prabha is adorned with flame tips and has a round chatara at the top.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Bronze sculpture",
    date: "c. 9th Century CE",
    location: "Eastern India",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.19_6173f5f1.jpg",
    title: "Buddha",
    dsc: "The bronze sculpture of Buddha is depicted seated on a double inverted lotus pedestal placed on a high pitha. He is seated in padmasana, with his hands in the gesture of bhumisparshamudra (touching the earth gesture) commonly known as ‘’earth-witness’’ Buddha, symbolizing the moment of his enlightenment.\nBuddha is shown here wearing a plain sanghati in a typical eastern fashion.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Bronze sculpture",
    date: "c. 10th Century CE",
    location: "Eastern India",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.19_47ca4594.jpg",
    title: "Harpist",
    dsc: "The image is of Harpist holding a harp in both hands, with gestures suggesting that he is engaged in playing the instrument. His dhoti falls down to his knees, and he is draped in a shawl-like upper garment covering his chest, shoulders and head. He is depicted standing on aa raised platform. Two panels of floral decorations visible at the top.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Sculpture",
    date: "2nd Century CE",
    location: "Taxila, Gandhara",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.20_15f8c755.jpg",
    title: "Fragmentary frieze with two ladies",
    dsc: "Two female figures are seated on a stool below the ledge with small, empty niches at the top. Both are cladded in Roman style costumes, but the hairstyle is typically Gandharan tied with hair bands. They wear simple bracelets and earrings. One is playing a long flute while the other has turned her head to her right to look at something.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Sculpture",
    date: "2nd Century CE",
    location: "Taxila",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.20_63c0dfb4.jpg",
    title: "Panchika and Hariti",
    dsc: "The sculpture is of Panchika and Hariti. Hariti is a yakshini, one of the mother goddesses, revered as a symbol of motherhood in Buddhism. She is sometimes shown along with her consort Panchika- a Yaksha general of Gandhara region. Together, they are revered as a protective deity, they are believed to bring prosperity to families.\nHere Panchika and Hariti are carved in deep relief against the back slab. Both are attired in tunics in western fashion and have a typical Gandharan hairstyle. They are wearing a simple necklace and bracelets. Panchika is holding a goblet in his right hand and money bag in the left. Hariti’s right-hand rests on his left thigh and her left hand supports a cornucopia.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Sculpture",
    date: "2nd Century CE",
    location: "Taxila",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.20_12a711b9.jpg",
    title: "Infant Buddha’s first bath",
    dsc: "The sculpture depicts infant Buddha’s first bath by Indra. Infant Buddha is depicted standing on a high stool supported by three decorative legs. His right hand is in abhaymudra. Indra is shown pouring water on Buddha’s head. He is wearing a dhoti and shawl. His curly hair is depicted in typical Gandharan style. Small tenon at top indicates that this sculpture must have been a part of larger sculpture",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Sculpture",
    date: "2nd Century CE",
    location: "Taxila",
  },
  {
    imgurl:
      "https://csmvs.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-12.09.21_3063cc3a.jpg",
    title: "Garland bearer",
    dsc: "This male figure is of a garland bearer holding a thick garland in his both hands. His facial features are very sharp. His curly tied hair is tied with a headband typical of Gandharan hairstyle. He is wearing a simple necklace and bracelets",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Sculpture",
    date: "2nd Century CE",
    location: "Taxila",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2023/08/90.8-31.jpg",
    title: "Buddhapada",
    dsc: "The footprints of the Buddha symbolise the Buddha’s presence, as they are believed to be the imprints where the Buddha actually touched the ground. At the same time, the Buddhapada signify the Buddha’s absence now that he has entered nirvana and thus are a reminder of the Buddhist ideal of non-attachment.\nThe Buddha’s footprints are usually depicted with the toes of tall one length and a dharma chakra (wheel) in the centre.\nThe left footprint of Buddha with Swastikas on the finger tips. The sole is decorated with the tri-ratna symbol surmounted with dharmachakras",
    collection: "Buddhist Art",
    artist: "Sculpture",
    objType: "Grey Schist",
    date: "Takht-i-Bahi, Gandhara (West Pakistan)",
    location: "N/A",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S-55.jpg",
    title: "Atlas",
    dsc: "This is an image of atlas or atlante. In the European architectural scheme, an atlas or atlante is used as a support which generally takes the place of a column or a pilaster. Similar to the concept of Bharvahakas in Indian iconography, he is depicted in human form. According to legend the Greek Atlas - The Titan was forced to hold the sky on his shoulders for eternity. The motif of Yaksha-atlante became frequent in Gandhara art.\nThis two-armed although broken at its forearms part is depicted with two wings at the back. He is shown with a muscular body and a bearded face. His two legs are broken.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "3rd Century CE",
    location: "Gandhara",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S-53.jpg",
    title: "Bodhisattva",
    dsc: "This is a stone sculpture of a Bodhisattva cladded in folded drapery. His hair is tied in two loops on the head. He is wearing necklaces, amulet-chain, armlets and earrings.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Sculpture",
    date: "3rd Century CE",
    location: "Gandhara (West Pakistan)",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/B-549.jpg",
    title: "Buddha",
    dsc: "This is an image of Buddha seated in Padmasana on a lotus pedestal resting on a rectangular bhadrapitha. He is shown in a deep meditation which is effectively expressed by the artist through his long, partially opened meditative eyes inlaid with silver and a subtle smile on his oval face. He has a straight blunt nose and thin lips. The earlobes are elongated but do not touch the shoulders. His hair is arranged in conventionalized curls is surmounted by the urnisha. The neck has three folds. His both hands are missing. His sanghati is wrapped around his left shoulder in folds. Continuing the tradition of late Gandhara style at Mirpur Khas. The artist has exposed the folds of an undergarment beneath the sanghati. An illegible word is inscribed on the pedestal.",
    collection: "Buddhist Art",
    artist: "NA",
    objType: "Figurine",
    date: "7-8th Century CE",
    location: "Kashmir",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/SI-105.jpg",
    title: "Epitaph engraved on Sarcophagus",
    dsc: "This inscription is an epitaph engraved on the sarcophagus which is said to have originally come from Persia but from which part of that country, it is not known. The Sarcophagus is a single rectangular surmounted by a replica of the grave similar to what we find in the cases of the tombs in India. The record is in two parts: the portion comprising only religious texts is inscribed on the four sides of the sarcophagus. The record contains the well-known Quranic Verse on the immortality of the god. This text is executed in ornamental Kufi of an intricate pattern whereby, the shafts of the letters carved in prominent relief with boldness of shape and outline, have been so interwoven forming a motif of beautiful floral design. The other part of record is engraved in relief in plain kufi. It records the third last chapter of Quran followed by an obituary notice of ‘Ali who passed away in the month of Rajab, A.H. 410 (November 1019 CE.).\nThe entire inscription read as-\ni) In the name of God, the compassionate, the Merciful. ‘Everyone that is thereon will pass away; There remaineth but the countenance of the Lord OF Might and Glory. May God’s blessing be upon (His prophet) Muhammad and his descendants.\nii) Say: he is Allah, the One! Allah the eternally Besought of all! He begotten not, nor was begotten. And there is none comparable upto Him.",
    collection: "COLLECTION",
    artist: "OBJECT TYPE",
    objType: "MATERIAL",
    date: "LOCATION",
    location: "DIMENSION",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/SI-6.jpg",
    title: "Wada Inscription",
    dsc: "This is a stone inscription from Wada, Thane district. It records donation of gardens and ponds to the temples of Koteshvara, Vasistheshvara and Siddheshvara by Simhadatta the Talavara, a high officer of Maurya king Dharmamaharaja Suketuvarman. One more thing to note here is, this is the only available stone inscription of the Mauryan dynasty ruling over Konkan from Puri (Gharapuri) during the span of 400 to 610 CE.",
    collection: "Inscriptions",
    artist: "Inscription Stone Inscription",
    objType: "Chlorite-mica schist",
    date: "H: 95 cm x base: 51 cm x W: 10.5 cm",
    location: "N/A",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S-328.jpg",
    title: "Varahi",
    dsc: "Here, the two-armed Varahi with a halo around her head stands with her face turned upward. She holds a club in her right hand and a child in her left. She is wearing a beautiful necklace, end of which is dangling between her breasts. She seems to be wearing a saree with a girdle reaching her feet; and a garland (vanamala) which hangs down to her knees. A buffalo, Varahi’s mount (vahana) stands behind her.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "9th Century CE",
    location: "Madhya Pradesh",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S-135.jpg",
    title: "Brahma",
    dsc: "This is a sculpture of three headed and four handed (Chaturbhuja) standing Brahma. His upper right hand holds sacrificial ladle (shruk) and his upper left hand holds a lotus bud. He is holding a Kamandalu in his principal left hand. The object in his principal right hand is damaged. A male and a female attendants can be seen on his either side. He is wearing a conical jatamukuta. He is shown wearing necklaces, bracelets and yajnopavita.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "7-8th Century CE",
    location: "Karnataka",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S-76.jpg",
    title: "Trivikrama",
    dsc: "This is a torso of Trivikrama. It was probably shadbhuja (six armed) sculpture, although all the arms are now broken. He is wearing a decorated kirita mukuta. He also wearing earring and a beaded necklace. His curly locks of hair are visible falling on his shoulders.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "Mid 6th Century CE",
    location: "Elephanta, Maharashtra",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S152.jpg",
    title: "Brahma",
    dsc: "This four-headed life-size sculpture is identified as an image of Brahma. He is adorned with various ornaments, a necklace, hollow cast earrings, a torque, a thick necklace and also wears the skin of an antelope and yajnopavita on his shoulder. The design of his moulded earrings has continued till today. Similar earrings are occasionally seen worn by some Koli women of this area who still prefer traditional ornamentation.\nThis is the only known figure from Elephanta which is carved in the round and is to be seen from all the four sides. Hence, it is probable that the sculpture was installed in the shrine for the devotees to do pradakshina or circumambulation.\nThe image is carved in the round only up to the lower part of the neck of the rear side. The artist has carved a smooth vertical slab at the back, probably to fix the image on a vertical support.",
    collection: "Sculptures",
    artist: "Sculpture",
    objType: "Basalt",
    date: "110 x 57 x 45 cms.",
    location: "N/A",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S75-edit.jpg",
    title: "Varuna with his Consort",
    dsc: "This sculpture is one of the most beautiful depictions of Varuna and his consort. Varuna has been associated with water right from the Rigvedic times. Water is the greatest boon of nature to mankind and Varuna is “Lord of the water”, as he is designated in the Vishnudharmottara. His association with water is clearly reflected in his iconography as well, particularly through his mount makara, an aquatic creature. In this sculpture, Varuna is seated with his consort Varunani to his right, on a padmapith in Lalitasana on his mount makara. He holds in his right hand a bowl full of ratnas or jewels, symbolic of the treasures of the ocean from where they emerged at the time of the churning of the ocean. His left hand rests on his lap. The noose with which he punishes the evil doer, is shown behind him. Varuna is adorned with a necklace, a waistband, armlets, kadas, yojnopavita, while his consort varuna is decorated with fewer ornaments. Rhythmic scallops indicating clouds also signifying Varuna’s association with waters are carved around them. The sculptor has also created an effect of waves generated by the forward movement of the makara. Elaborately carved tail of the makara adds design element to the sculpture. This image probably has occupied the western wall of a temple as Varuna is the guardian deity of the Western Direction.",
    collection: "Sculptures",
    artist: "Sculpture",
    objType: "Basalt",
    date: "Karnataka",
    location: "86 x 56 x 20 cms",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/S-147.jpg",
    title: "Kshetrapala",
    dsc: "This is a Chaturbhuja (four-armed) sculpture of Kshetrapala. He is holding a bow in his upper right hand and an arrow in his upper left hand. His left principal hand holds a bell and his right principal hand holds a hammer-like object. His popping eyes and his fangs expresses the fierce nature of the deity. The Torana at his back is decorated with floral scrolls.",
    collection: "Sculptures",
    artist: "NA",
    objType: "Sculpture",
    date: "12th Century CE",
    location: "Karnataka",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/78.8.jpg",
    title: "St. Sebastian",
    dsc: "Born in the 3rd century CE in Gaul (Narbonne in present France), St. Sebastian was persecuted during\nthe reign of Emperor Diocletian by being shot with arrows. St. Sebastian was invoked against the plague\nsince the middle ages. Many chapels, requiring numerous images showing his martyrdom were raised\nin his honour in Portuguese territories",
    collection: "Indian Decorative Art",
    artist: "NA",
    objType: "Figurine",
    date: "18th century CE",
    location: "Goa",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/78.14.jpg",
    title: "St. Francis Xavier",
    dsc: "St. Francis Xavier is called the Apostle of the Indies, on account of his successful missions in India, Japan\nand China. After his death in China, his body was brought back to Goa and placed in the Basilica of Bom\nJesus; where it still remains",
    collection: "Indian Decorative Art",
    artist: "Figurine",
    objType: "Ivory",
    date: "Goa",
    location: "N/A",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/L-82.2-110.jpg",
    title: "St. Roch",
    dsc: "St. Roch has been evoked since the 14th century against the plague, leprosy and cholera that periodically raged throughout Portugal, particularly in Lisbon, where his cult gained a large following. From that city the devotion spread to the overseas territories under Portuguese jurisdiction. He is usually depicted as a pilgrim.",
    collection: "Indian Decorative Art",
    artist: "NA",
    objType: "Figurine",
    date: "18th century CE",
    location: "Goa",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/L-82.2-109.jpg",
    title: "St. John the Baptist",
    dsc: "St. John the Baptist is depicted as a desert hermit as mentioned in the Bible. The sculptor has taken few\nartistic liberties in the depiction of the beast-skin that is shown as a full garment with wide sleeves and of his long, tidy hair and not adopting the unkempt look more in line with the saint's life. He is portrayed with a book; symbolising the Scriptures and a lamb; symbolising Jesus",
    collection: "Indian Decorative Art",
    artist: "Figurine",
    objType: "Polychrome Wood",
    date: "Goa",
    location: "N/A",
  },
  {
    imgurl: "ploads/2024/04/L-87.20.jpg",
    title: "St. Nicholas of Tolentino",
    dsc: "St. Nicholas of Tolentino (1245 -1305 CE) was an Augustinian preacher, and is invoked as a protector\nagainst plague. He is depicted as a young man wearing the Augustinian dark habit with its hood, wide\nsleeves, cape over it and leather belt with long end, and sports a monastic tonsure. He seems to hold a\nbook, which could be his order's regulations, and has a large star shining on his chest – his true personal\nattribute.",
    collection: "Indian Decorative Art",
    artist: "Figurine Sculpture",
    objType: "Polychrome Wood",
    date: "Diu-Daman",
    location: "N/A",
  },
  {
    imgurl: "https://csmvs.in/wp-content/uploads/2024/04/L-82.2-111.jpg",
    title: "St. Peter",
    dsc: "St. Peter, the apostle (martyred in 64 CE) became the leader of the apostles (disciples of Jesus). He was\nfamous for his healing powers. He is usually depicted with a tonsure or a bald patch and with dark beard.\nThe Keys of Heaven hang from his waist while he holds a Bible in his left hand.",
    collection: "Indian Decorative Art",
    artist: "Figurine",
    objType: "Polychrome Wood",
    date: "Goa",
    location: "N/A",
  },
];

export default data;
